rebelot/kanagawa.nvim

- README.md
- extras/kanagawa.itermcolors
Thanks for the great-looking theme! This PR adds a theme for iTerm based on the Kitty theme. iTerm is missing some of the options Kitty has (for example, inactive tab colors seem to be automatically calculated from the active tab color) but it should be pretty similar:
> Add iTerm theme

- extras/kanagawa.conf
Right now the foreground colors used in kitty tabs make the text very hard to read. I used lighter colors from the palette to improve contrast/legibility
> fix: improve kitty tab contrast

- README.md
- extras/pywal-theme.json
[pywal](https://github.com/dylanaraps/pywal) project allows generating themes for many programs.
Having this single file will allow generating themes for all
programs supported by pywal using below command:
wal -e -t -s --theme extras/pywal-theme.json # generated configs are in ~/.cache/wal/
List of supported programs can be found [here](https://github.com/dylanaraps/pywal/wiki/Customization)
> Add pywal theme

- README.md
- extras/foot_kanagawa.ini
This is basically a straight port of the Alacritty theme for use with [foot](https://codeberg.org/dnkl/foot).
I also sorted the extras list since that'll make it easier to find things as more extras are added.
> Add foot colorscheme

- extras/kanagawa.fish
Add theme for [Fish](https://fishshell.com/). This fixes https://github.com/rebelot/kanagawa.nvim/issues/26
> Add Fish shell theme

- README.md
- extras/windows_terminal.json
Color scheme support for the Windows Terminal, which uses a `settings.json` to set color schemes and other terminal settings.
This has to be added to the existing list of color schemes ("schemes": [...]) to work.
> Theme config for Windows Terminal

- lua/kanagawa/hlgroups.lua
Closes #50 by replacing `unpack` with `vim.tbl_extend`. The builtin `unpack` function is used for list-like tables according to the [docs](http://www.lua.org/manual/5.1/manual.html#pdf-unpack).
First attempt at creating a pull request on Github, so apologies if format or anything else is off.
> fix(hlgroups): use vim.tbl_extend to apply config styles

- lua/kanagawa/colors.lua
- lua/kanagawa/hlgroups.lua
- lua/kanagawa/init.lua
This is also the annotation style that the lua-language-server
implements.
This gives a bit richer diagnostics and autocompletions, for example:
> fix: use EmmyLua-style code annotations

- lua/kanagawa/hlgroups.lua
Fix #80 by defining the tag, tag.delimiter, and tag.attribute groups.
Before:
After:
> Fix missing tag highlights

- palette.py
This script to output the image's color palette is incredibly handy. However, my only nitpick is the order in which the colors are exported. I added an optional argument to allow the export of the palette ordered by Hue (Rainbow like).
[Ordering color is complicated](https://www.alanzucconi.com/2015/09/30/colour-sorting/).
The change is smaller than it actually appears in the diff. I ran `isort`, to sort the imports, and `black`, to format the script.
> Allow for color ordering

- lua/kanagawa/hlgroups.lua
fixes: https://github.com/rebelot/kanagawa.nvim/issues/91
after:
> fix(hlgroups): symbol

- lua/kanagawa/hlgroups.lua
Before:
After:
(Helix as base):
> fix(hlgroups): tag attribute color

- extras/kanagawa.fish
On 8/16 color terminals, like the Linux console, the color interpolation on the 24 bit colors in this colorscheme lead to undesirable results, like the prefix of a valid command looking the same as the completion suggestion.
The set_color command in fish supports a fallback color as a second positional argument, which is documented here:
https://fishshell.com/docs/current/cmds/set_color.html
This commit introduces fallback colors which are recognized by 16 color terminals. On the Linux console I tested this on, there is no difference between the bright and non-bright colors, except for black, whose bright variant is gray.
I did not test this on a 256-color terminal. There it might be preferable to have no fallback but use interpolation instead.
> Add fallback colors to fish highlighting

- extras/kanagawa_dragon.itermcolors
This PR adds an itermcolors file for the kanagawa dragon theme, which can be imported into iTerm2.
> add kanagawa_dragon iTerm theme

- lua/kanagawa/highlights/editor.lua
Allow control of undercurls from config as advertised. Fix #115
> fix(theme) Use config.undercurl when setting up highlights

- lua/kanagawa/highlights/treesitter.lua
This supersedes #99 since everything was refactored. This adds in
support for highlighting of `NOTE` since currently it's not supported.
> feat: add in support for Note

- lua/kanagawa/highlights/treesitter.lua
The `@keyword.exception` highlight group was missing the `@` symbol. This PR adds it to match the other keyword groups and to match what [treesitter uses](https://github.com/nvim-treesitter/nvim-treesitter/blob/488e39a8f1fcb7935deaaf1852e3d6c28ca253d0/CONTRIBUTING.md#keywords).
Love this theme!
> Fix missing "@" for @keyword.exception

- lua/kanagawa/highlights/plugins.lua
Hi! I would like to add explicit support for [mini.nvim](https://github.com/echasnovski/mini.nvim).
Basic choices are taken from either highlight groups to which 'mini.nvim' makes default links or from analogous plugins.
Differences from default linked groups:
- 'mini.indentscope' is based on 'indent-blankline'.
- 'mini.jump2d' takes color from "SpellRare" to be consistent with 'mini.jump'. Using `nocombine = true` to be consistent (not have italic labels on italic text).
- 'mini.starter' is based on 'dashboard.lua', 'whichkey.lua', 'telescope.lua', and personal choices:
- `MiniStarterSection` is chosen to be visible (as from "Special" highlight group).
- `MiniStarterItemBullet` is as border.
- `MiniStarterItemPrefix` and `MiniStarterQuery` are based on "warning" and "info" diagnostic …
> Add explicit support for 'mini.nvim'

- lua/kanagawa/highlights/plugins.lua
Neotest highlight groups use cterm color names.
> feat: adds highlight group overrides for Neotest

- README.md
Makes the part about modifying `hlgroups` a little more beginner friendly.
Changes this:
You can also conveniently add/modify `hlgroups` using the `config.overrides` option.
To this:
You can also conveniently add/modify _**any**_ `hlgroups` using the `config.overrides` option _**, allowing you to customize the looks of specific built-in elements, or any other external plugins that provides `hlgroups`. (See `:help highlight` for more information on `hlgroups`.)**_
> Readme: Add beginner-friendly info about hlgroups

- README.md
Thanks for this awesome theme!
@rebelot, I stumbled upon https://github.com/rebelot/kanagawa.nvim/issues/220 and [loved your solution there](https://github.com/rebelot/kanagawa.nvim/issues/220#issuecomment-2012456576) using the built-in kanagawa's functions. I figured it might be a good addition to the "Common customizations" section of the README. I've seen this style in other themes (including the very popular tokyonight), so it might be a customization that others might be looking for as well.
I've slightly refactored the code to extract the common logic to a callback.
> Add hint on tinting diagnostic messages

- README.md
- extras/ghostty/kanagawa-dragon
- extras/ghostty/kanagawa-lotus
- extras/ghostty/kanagawa-wave
I have added the three kanagawa themes (dragon, wave and lotus) for ghostty.
PS: it follows the same structure as in this [PR](#269)
> feat(terminal): added kanagawa themes for ghostty

- lua/kanagawa/highlights/lsp.lua
This commit ensures that LSP-identified comments are highlighted as comments. Previously, `{ fg = "none" }` was disabling any special highlighting for LSP-identified comments.
I believe this link is the default since 0.9 (here [default runtime/colors/vim.lua#L197](https://github.com/neovim/neovim/blob/56fabcadb6df46c70402e4f9cd1b851856fb57e9/runtime/colors/vim.lua#L197)).
I was bumping into this with preprocessor blocks in C code. With `fg = "none"`, inactive regions would not get any special highlighting but also wouldn't get de-emphasized (or grayed out like comments):
With this commit, the unused block gets styled like any other comment:
> fix(lsp): link @lsp.type.comment semantic token to Comment hlgroup
